=== g-biroli/JavaScriptStudies/Lenguaje/TiposFicheros/validacion.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT asignatura (titulo+, tema+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT tema (clases+)>
<!ATTLIST tema titulo CDATA #REQUIRED>
<!ELEMENT clases (clase+)>
<!ELEMENT clase (#PCDATA)>
<!ATTLIST clase titulo CDATA #REQUIRED>

=== g-biroli/JavaScriptStudies/Lenguaje/TiposFicheros/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE asignatura SYSTEM "./validacion.dtd">
<asignatura>
    <titulo> Lenguaje de marcas </titulo>
    <tema titulo="XML">
        <clases>
            <clase titulo="Introduccion">Introduccion a los lenguajes XML</clase>
            <clase titulo="Estructura">Estructura de un fichero XML</clase>
            <clase titulo="Usos">Usos que tienen los ficheros XML</clase>
        </clases>
    </tema>
    <tema titulo="HTML">
        <clases>
            <clase titulo="Introduccion">Introduccion a HTMLL</clase>
            <clase titulo="Etiquetas">Definicion y uso de cada una de las etiquetas</clase>
            <clase titulo="CSS">Usos de CSS sobre HTML</clase>
        </clases>
    </tema>
    <tema titulo="Dinasmismo">
        <clases>
            <clase titulo="Introduccion">Introduccion a JS</clase>
            <clase titulo="DOM">Definicion y uso de DOM</clase>
            <clase titulo="Json">Usos que tienen los ficheros XML</clase>
        </clases>
    </tema>

</asignatura>
